config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'posts#index'
  get '/explore', to: 'posts#explore'

  resources :users, param: :username, only: [:index, :show, :edit, :update] do
    resources :posts, except: [:index]
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  validates :latitude, presence: true
  validates :longitude, presence: true
  validate :photo_validation

  def photo_validation
    if photo.attached?
      if !photo.content_type.in?(%w(image/jpeg image/png))
        errors.add(:photo, 'must be jpeg or png')
      end
    else
      errors.add(:photo, 'must be attached')
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, presence: true
  validates :followee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar

  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followee_id', dependent: :destroy

  has_many :followees, through: :active_relationships
  has_many :followers, through: :passive_relationships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def follow(other)
    active_relationships.create(followee_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followee_id: other.id).destroy
  end

  def following?(other)
    folowees.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :avatar, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  def index
    redirect_to explore_url unless user_signed_in?

    @posts = Post.order('created_at desc').limit(5).where(user: [current_user, *current_user.followees]).includes(:user).with_attached_photo
    @markers = @posts.map {|post| to_marker(post)}
  end

  def explore
    @posts = Post.limit(5).includes(:user).with_attached_photo
    @markers = @posts.map {|post| to_marker(post)}

    render 'posts/index'
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def post_params
      params.require(:post).permit(:latitude, :longitude, :photo)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    follower = User.find(params[:follower_id])
    followee = User.find(params[:followee_id])

    if relationship = follower.follow(followee)
      render json: { status: 'ok', relationship_id: relationship.id }
    else
      render json: { status: 'ng' }
    end
  end

  def destroy
    Relationship.find(params[:id]).destroy

    render json: { status: 'ok' }
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    resource.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_avatar.png')), filename: 'default_avatar.jpg', content_type: 'image/png')
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include PostsHelper

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
    @posts = @user.posts
    @markers = @posts.map {|post| to_marker(post)}
    @relationship_id = user_signed_in? && Relationship.where(follower_id: current_user.id).where(followee_id: @user.id).first&.id

    puts @relationship_id
  end

  def edit
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def to_marker(post)
    {
        post_id: post.id,
        lat: post.latitude,
        lng: post.longitude,
        photo_url: url_for(post.photo),
        post_url: user_post_path(user_username: post.user.username, id: post.id)
    }
  end

  def menu_item_class(path)
    request.path == path ? 'active item' : 'item'
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rekall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDK9mn7ZW6XACU549yjgITeJ-ajyeld0QM"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
  </head>

  <body>

    <div class="ui top fixed menu">
      <%= link_to 'REKALL', root_path, class: 'item' %>

      <div class="right menu">
        <% if user_signed_in? %>
          <%= link_to current_user.username, user_path(username: current_user.username), class: 'item' %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'item' %>
          <%= link_to edit_user_registration_path(current_user), class: 'item' do %>
            <i class="cog icon"></i>
          <% end %>
          <%= link_to new_user_post_path(current_user), class: 'item' do %>
            <i class="plus icon"></i>
          <% end %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'item' %>
          <%= link_to 'Log in', new_user_session_path, class: 'item' %>
        <% end %>
      </div>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/index.html.erb
<div id="map"></div>

<div class="ui doubling four link cards">
  <% @photos.each do |photo| %>
    <div class="card">
      <div class="image">
        <%= image_tag photo.image %>
      </div>
      <div class="content">
        <div class="description">
          hahaha test
        </div>
      </div>
      <div class="extra content">
        extra
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
    let map = new GMaps({
        div: '#map',
        lat: 35.6896,
        lng: 139.6921,
    });

    GMaps.geolocate({
        success: function (position) {
            map.setCenter(position.coords.latitude, position.coords.longitude);
        },
        error: function (error) {
        },
        not_supported: function () {
        },
    });

    let markers = <%= @markers.to_json.to_s.html_safe %>;
    markers.forEach(function(marker) {
        map.addMarker({
            lat: marker.lat,
            lng: marker.lng,
            infoWindow: {
                content: `<img src=${marker.image_url} height='100' />`
            },
            mouseover: function (e) {
                this.infoWindow.open(map, this);
            },
            mouseout: function (e) {
                this.infoWindow.close();
            },
            click: function (e) {
                window.location.href = `/photos/${marker.photo_id}`
            }
        })
    });
</script>

app/views/photos/new.html.erb
<h2>Post new photo</h2>

<%= form_for @photo, html: { class: 'ui form' } do |f| %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <div id="map"></div>
  </div>

  <%= f.submit 'Submit', class: 'ui orange button' %>
<% end %>

<script type="text/javascript">
    let mapNew;
    if (!mapNew) {
       mapNew = new GMaps({
            div: '#map',
            lat: 35.6896,
            lng: 139.6921,
        });
    }

    navigator.geolocation.getCurrentPosition(position => {
        const { latitude, longitude } = position.coords;
        mapNew.setCenter(latitude, longitude);
    }, error => {

    });

    GMaps.on('click', mapNew.map, function(e) {
        mapNew.removeMarkers();

        const lat = e.latLng.lat();
        const lng = e.latLng.lng();

        mapNew.addMarker({
            lat,
            lng,
        });

        document.getElementById('photo_latitude').value = lat;
        document.getElementById('photo_longitude').value = lng;
    });
</script>

app/views/posts/index.html.erb
<div class="ui two item menu">
  <%= link_to 'Timeline', root_path, class: menu_item_class(root_path) %>
  <%= link_to 'Explore', explore_path, class: menu_item_class(explore_path) %>
</div>

<div id="map"></div>

<div class="ui doubling four link cards">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="image">
        <%= image_tag post.photo %>
      </div>
      <div class="content">
        <div class="description">
          hahaha test
        </div>
      </div>
      <div class="extra content">
        extra
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
    let map = makeMap();
    setMapCenter(map);

    let markers = <%= @markers.to_json.to_s.html_safe %>;
    locateMarkers(markers, map);
</script>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= form_for @post, url: user_posts_path(current_user), html: { class: 'ui form' } do |f| %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <div id="map"></div>
  </div>

  <%= f.submit 'Submit', class: 'ui orange button' %>
<% end %>

<script type="text/javascript">
    let map = makeMap();
    setMapCenter(map);

    GMaps.on('click', map.map, function(e) {
        map.removeMarkers();

        const lat = e.latLng.lat();
        const lng = e.latLng.lng();

        map.addMarker({
            lat,
            lng,
        });

        document.getElementById('post_latitude').value = lat;
        document.getElementById('post_longitude').value = lng;
    });
</script>

app/views/posts/show.html.erb
<%= image_tag @post.photo, width: '100%' %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>,
      <%= user.posts.count %> posts
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<%= image_tag @user.avatar.variant(resize: '60x60'), style: 'border-radius: 50%;' %>
<p><%= @user.posts.count %> posts</p>
<p><%= @user.followers.count %> followers</p>
<p><%= @user.followees.count %> followees</p>

<div id="follow-button">
  <button
    v-if="isShowing"
    class="ui button"
    v-bind:class="color()"
    v-on="{ click: isFollowing ? handleUnfollow : handleFollow }"
    v-bind:disabled="isFetching"
  >
    {{ message() }}
  </button>
</div>

<div id="map"></div>

<div class="ui doubling four link cards">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="image">
        <%= image_tag post.photo %>
      </div>
      <div class="content">
        <div class="description">
          hahaha test
        </div>
      </div>
      <div class="extra content">
        extra
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
    let map = makeMap();
    setMapCenter(map);

    let markers = <%= @markers.to_json.to_s.html_safe %>;
    locateMarkers(markers, map);

    var followButton = new Vue({
        el: '#follow-button',
        data: {
            isShowing: <%= user_signed_in? && current_user != @user %>,
            isFollowing: <%= !@relationship_id.nil? %>,
            currentUserId: <%= user_signed_in? ? current_user.id : -1 %>,
            userId: <%= @user.id %>,
            relationshipId: <%= @relationship_id.nil? ? -1 : @relationship_id %>,
            isFetching: false,
        },
        methods: {
            message: function() {
                return this.isFollowing ? 'Unfollow' : 'Follow';
            },
            color: function() {
                return this.isFollowing ? 'red' : 'teal';
            },
            handleFollow: function() {
                followButton.isFetching = true;
                fetch('/relationships', {
                    method: 'post',
                    body: JSON.stringify({
                        follower_id: this.currentUserId,
                        followee_id: this.userId,
                    }),
                    headers: { 'Content-Type': 'application/json', },
                    credentials: 'same-origin'
                }).then(function (response) {
                    return response.json();
                }).then(function (data) {
                    followButton.isFetching = false;
                    followButton.isFollowing = true;
                    followButton.relationshipId = data.relationship_id;
                });
            },
            handleUnfollow: function() {
                followButton.isFetching = true;
                fetch(`/relationships/${this.relationshipId}`, {
                    method: 'delete',
                    credentials: 'same-origin'
                }).then(function(response) {
                    return response.json();
                }).then(function(data) {
                    followButton.isFetching = false;
                    followButton.isFollowing = false;
                });
            }
        }
    });
</script>